#!/usr/bin/env bash
#
# deploy.sh — deploy and wire up the StellarFund contracts on a Soroban network.
#
# Deploys Treasury, Campaign, and Factory, then initializes them so that:
#   - Treasury authorizes the Campaign contract to move funds
#   - Campaign is wired to the Factory (creator) and Treasury (custody)
#   - Factory is wired to the Campaign and Treasury
#
# Contract IDs are written to deployments/<network>.json and a frontend .env.
#
# Usage:
#   ./scripts/deploy.sh <source-account> [network]
#
# Example:
#   ./scripts/deploy.sh alice testnet
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SOURCE="${1:-}"
NETWORK="${2:-testnet}"

if [[ -z "$SOURCE" ]]; then
  echo "Usage: ./scripts/deploy.sh <source-account> [network]" >&2
  exit 1
fi

TARGET="wasm32v1-none"
OUT_DIR="$ROOT_DIR/target/$TARGET/release"
DEPLOY_DIR="$ROOT_DIR/deployments"
mkdir -p "$DEPLOY_DIR"

# Native XLM Stellar Asset Contract per network (used as the donation token).
case "$NETWORK" in
  testnet)
    NATIVE_TOKEN="CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"
    ;;
  mainnet|public)
    NATIVE_TOKEN="CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA"
    ;;
  *)
    NATIVE_TOKEN="${NATIVE_TOKEN:-}"
    ;;
esac

if [[ -z "$NATIVE_TOKEN" ]]; then
  echo "Set NATIVE_TOKEN env var for network '$NETWORK'." >&2
  exit 1
fi

echo "▶ Ensuring contracts are built…"
"$ROOT_DIR/scripts/build.sh"

ADMIN_ADDR="$(stellar keys address "$SOURCE")"
echo "▶ Deploying as: $ADMIN_ADDR (network=$NETWORK)"

deploy() {
  local wasm="$1"
  stellar contract deploy \
    --wasm "$wasm" \
    --source "$SOURCE" \
    --network "$NETWORK" 2>/dev/null
}

echo "▶ Deploying Treasury…"
TREASURY_ID="$(deploy "$OUT_DIR/stellarfund_treasury.wasm")"
echo "  ✓ Treasury:  $TREASURY_ID"

echo "▶ Deploying Campaign…"
CAMPAIGN_ID="$(deploy "$OUT_DIR/stellarfund_campaign.wasm")"
echo "  ✓ Campaign:  $CAMPAIGN_ID"

echo "▶ Deploying Factory…"
FACTORY_ID="$(deploy "$OUT_DIR/stellarfund_factory.wasm")"
echo "  ✓ Factory:   $FACTORY_ID"

invoke() {
  stellar contract invoke \
    --id "$1" --source "$SOURCE" --network "$NETWORK" -- "${@:2}"
}

echo "▶ Initializing Treasury (authorizes Campaign to move funds)…"
invoke "$TREASURY_ID" initialize \
  --admin "$ADMIN_ADDR" --token "$NATIVE_TOKEN" --authorized "$CAMPAIGN_ID"

echo "▶ Initializing Campaign (wired to Factory + Treasury)…"
invoke "$CAMPAIGN_ID" initialize \
  --admin "$ADMIN_ADDR" --factory "$FACTORY_ID" --treasury "$TREASURY_ID"

echo "▶ Initializing Factory (wired to Campaign + Treasury)…"
invoke "$FACTORY_ID" initialize \
  --admin "$ADMIN_ADDR" --campaign "$CAMPAIGN_ID" --treasury "$TREASURY_ID"

OUT_JSON="$DEPLOY_DIR/$NETWORK.json"
cat > "$OUT_JSON" <<EOF
{
  "network": "$NETWORK",
  "admin": "$ADMIN_ADDR",
  "token": "$NATIVE_TOKEN",
  "contracts": {
    "treasury": "$TREASURY_ID",
    "campaign": "$CAMPAIGN_ID",
    "factory": "$FACTORY_ID"
  }
}
EOF
echo "▶ Wrote $OUT_JSON"

ENV_OUT="$ROOT_DIR/frontend/.env.local"
cat > "$ENV_OUT" <<EOF
# Auto-generated by scripts/deploy.sh — do not edit by hand.
NEXT_PUBLIC_STELLAR_NETWORK=$NETWORK
NEXT_PUBLIC_SOROBAN_RPC_URL=https://soroban-$NETWORK.stellar.org
NEXT_PUBLIC_NETWORK_PASSPHRASE=$( [[ "$NETWORK" == "testnet" ]] && echo "Test SDF Network ; September 2015" || echo "Public Global Stellar Network ; September 2015" )
NEXT_PUBLIC_NATIVE_TOKEN=$NATIVE_TOKEN
NEXT_PUBLIC_FACTORY_ID=$FACTORY_ID
NEXT_PUBLIC_CAMPAIGN_ID=$CAMPAIGN_ID
NEXT_PUBLIC_TREASURY_ID=$TREASURY_ID
EOF
echo "▶ Wrote $ENV_OUT"

echo "✅ Deployment complete."
